server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_order_db   # overridden by SPRING_DATASOURCE_URL env var in Docker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    # import: optional:configserver:http://config-server
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # overridden by EUREKA_CLIENT_SERVICEURL_DEFAULTZONE env var in Docker

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      user-service:
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: refresh